export enum BlogCategory {
  TRAVEL_TIPS = 'TRAVEL_TIPS',
  DESTINATION_GUIDE = 'DESTINATION_GUIDE',
  SOLO_TRAVEL = 'SOLO_TRAVEL',
  ROAD_TRIPS = 'ROAD_TRIPS',
  ADVENTURE = 'ADVENTURE',
  CULTURAL = 'CULTURAL',
  NATURE = 'NATURE',
  GENERAL = 'GENERAL',
}
