export enum TourCategory {
  ADVENTURE = 'ADVENTURE',
  BEACH = 'BEACH',
  LEISURE = 'LEISURE',
  CULTURAL = 'CULTURAL',
  NATURE = 'NATURE',
  SPIRITUAL = 'SPIRITUAL',
  TREKKING = 'TREKKING',
  WILDLIFE = 'WILDLIFE',
  DESTINATION_GUIDE = 'DESTINATION_GUIDE',
  TRAVEL_TIPS = 'TRAVEL_TIPS',
  SOLO_TRAVEL = 'SOLO_TRAVEL',
  ROAD_TRIPS = 'ROAD_TRIPS',
}
